version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./bsop_fast/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./bsop_fast:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./bsop_next/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bsop_next:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true  # Enable file watching in Docker on some systems
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge